name: release

on:
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Build 
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          pyinstaller fig2sketch.py -y --onefile
      - name: Create folder and adjust permissions
        run: |
          mkdir dist/figma2sketch-linux
          mv dist/fig2sketch dist/figma2sketch-linux/
          chmod +x dist/figma2sketch-linux/fig2sketch
      - name: Zip directory
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: figma2sketch-linux.zip
      - name: Upload artifact    
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: figma2sketch-linux.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Build 
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          pyinstaller fig2sketch.py -y --onefile
      - name: Create folder and adjust permissions
        run: |
          mkdir dist/figma2sketch-windows
          mv dist/fig2sketch.exe dist/figma2sketch-windows/
          chmod +x dist/figma2sketch-windows/fig2sketch.exe
      - name: Zip directory
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: figma2sketch-windows.zip
      - name: Upload artifact    
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: figma2sketch-windows.zip

  build-macos-x86_64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Build 
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          pyinstaller fig2sketch.py -y --onefile --target-arch x86_64
      - name: Create folder and adjust permissions
        run: |
          mkdir dist/figma2sketch-macos
          mv dist/fig2sketch dist/figma2sketch-macos/
          chmod +x dist/figma2sketch-macos/fig2sketch
      - name: Zip directory
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: figma2sketch-macos-x86_64.zip
      - name: Upload artifact    
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: figma2sketch-macos-x86_64.zip

  build-macos-arm64:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
          architecture: x64 # Otherwise the runner will try to download Python arm64, which is not available. x64 has support for both archs (universal2).
      - name: Build 
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          pyinstaller fig2sketch.py -y --onefile --target-arch arm64
      - name: Create folder and adjust permissions
        run: |
          mkdir dist/figma2sketch-macos
          mv dist/fig2sketch dist/figma2sketch-macos/
          chmod +x dist/figma2sketch-macos/fig2sketch
      - name: Zip directory
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: figma2sketch-macos-arm64.zip
      - name: Upload artifact    
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: figma2sketch-macos-arm64.zip

  build-macos-universal:
    needs: [ build-macos-x86_64, build-macos-arm64 ]
    runs-on: macos-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: builds
      - name: Create universal binary with lipo
        run: |
          mkdir x86_64
          mkdir arm64
          mkdir -p dist/figma2sketch-universal
          unzip figma2sketch-macos-x86_64.zip -d x86_64/
          unzip figma2sketch-macos-arm64.zip -d arm64/
          lipo -create x86_64/figma2sketch-macos/fig2sketch arm64/figma2sketch-macos/fig2sketch -output dist/figma2sketch-universal/fig2sketch
      - name: Zip directory
        uses: vimtor/action-zip@v1
        with:
          files: dist/
          dest: figma2sketch-macos-universal.zip
      - name: Upload artifact    
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: figma2sketch-macos-universal.zip


  create-release:
    needs: [ build-linux, build-windows, build-macos-x86_64, build-macos-arm64, build-macos-universal ]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create release
        id: create_release
        uses: rymndhng/release-on-push-action@v0.27.0
        with:
          bump_version_scheme: patch
          tag_prefix: v
          use_github_release_notes: true
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: builds
      - name: Upload release assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: '*zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.create_release.outputs.tag_name }}
